In [1]:
import numpy as np

In [2]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [3]:
x1

array([5, 0, 3, 3, 7, 9])

## Sub arrays as no copy views

In [5]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [6]:
x2_sub = x2[:2 ,:2]   #array_name[start:end]
print(x2_sub)

[[3 5]
 [7 6]]


In [7]:
x2_sub[0,1] = 88

In [8]:
print(x2_sub)

[[ 3 88]
 [ 7  6]]


In [9]:
x2

array([[ 3, 88,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## Creating copies of arrays

In [10]:
x2

array([[ 3, 88,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [12]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[ 3 88]
 [ 7  6]]


In [13]:
x2_sub_copy[0,1] =99
print(x2_sub_copy)

[[ 3 99]
 [ 7  6]]


In [14]:
x2

array([[ 3, 88,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Reshaping the Arrays

In [15]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
grid2 = np.arange(1,13).reshape((2,3,2))
print(grid2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, -1)

In [20]:
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


#### flattening the array

In [21]:
newarr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
newarr2 = arr.reshape(-1)

In [23]:
newarr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
x = np.array([1,2,3])

x.reshape((1,3))

array([[1, 2, 3]])

In [25]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [26]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [27]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

## Concatenation of Arrays

In [30]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([99, 9 , 99])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [31]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99,  9, 99])

In [32]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])

np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [33]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [34]:
print(x)
print(grid)

[1 2 3]
[[1 2 3]
 [4 5 6]]


#### Vertically Stacks the array

In [35]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

#### Horizontally Stack the array

In [37]:
# all arrays should be of same dimension
np.hstack([grid, grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])