# Computation on NumPy Arrays: Universal Functions


<div class="alert alert-info">Computation on NumPy arrays can be very fast, or it can be very slow</div>
<div class="alert alert-danger">The key to making it fast is to use vectorized operations, generally implemented through Num‐
Py’s universal functions (ufuncs).</div>
<div class="alert alert-success">NumPy’s ufuncs,can be used to make repeated calculations on array elements</div>



## The Slowness of Loops

In [1]:
import numpy as np

In [10]:
# Example without ufunc
def sum_arr():
    x = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    y = [21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
    z = []
    for i,j in zip(x,y):
        z.append(i+j)
    print(z)
    
sum_arr()

[22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60]


In [4]:
%timeit sum_arr()

5.08 µs ± 536 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
# Example with ufunc
def sum_arr2():
    x = np.arange(20)
    y = np.arange(21,41)
    print(x)
    print(y)
    z = x+y
    print(z)
    
sum_arr2()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59]


In [8]:
%timeit sum_arr2()

2.79 µs ± 278 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Introducing UFuncs

💠NumPy provides a convenient interface into just this kind of statically typed, compiled routine. 
💠 This is known as a vectorized operation.

### Array arithmetic

🔶NumPy’s ufuncs feel very natural to use because they make use of Python’s native arithmetic operators.

🔶The standard addition, subtraction, multiplication, and division
can all be used


In [18]:
x = np.arange(4)
print("x  = ", x)
print("x + 5 = ", x + 5 )
print("x - 5 = ", x - 5 )
print("x * 5 = ", x * 5 )
print("x / 5 = ", x / 5 )
print("x // 5 = ", x // 5 ) #floor division

x  =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 5 =  [ 0  5 10 15]
x / 5 =  [0.  0.2 0.4 0.6]
x // 5 =  [0 0 0 0]


In [19]:
#negation
print("-x", -x )
#exponentiation
print("x ** 2 ", x ** 2 )
# modulus
print("x % 2 = ", x % 2 )

-x [ 0 -1 -2 -3]
x ** 2  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [20]:
-(0.5*x +1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [21]:
np.add(x,5)

array([5, 6, 7, 8])

### Absolute value

In [28]:
x = np.array([-2, -1, 0, 1, 2]) 
np.abs(x)

array([2, 1, 0, 1, 2])

In [29]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)  # sqrt(3^2 - 4^2)

array([5., 5., 2., 1.])

### Trigonometric functions

In [34]:
# start by defining an array of angles
theta = np.linspace(0, np.pi , 3)
print("theta = ", theta)

theta =  [0.         1.57079633 3.14159265]


In [37]:
# compute some trigonometric functions on these values:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [39]:
print("arcsin(theta) = ", np.arcsin(theta))
print("arccos(theta) = ", np.arccos(theta))
print("arctan(theta) = ", np.arctan(theta))

arcsin(theta) =  [ 0. nan nan]
arccos(theta) =  [1.57079633        nan        nan]
arctan(theta) =  [0.         1.00388482 1.26262726]


f:\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.
f:\python37\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in arccos
  


### Exponents and logarithms

🌺 Another common type of operation available in a NumPy ufunc are the exponentials

In [40]:
x = [1, 2, 3]
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [41]:
x = [1, 2, 4, 10]
print("x = ", x)
print("ln(x) = ", np.log(x))
print("ln2(x) = ", np.log2(x)) #base2
print("ln10(x) = ", np.log10(x)) #base 10

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
ln2(x) =  [0.         1.         2.         3.32192809]
ln10(x) =  [0.         0.30103    0.60205999 1.        ]


### Specialized ufuncs

🌷Another excellent source for more specialized and obscure ufuncs is the submodule <b> scipy.special.

## Advanced Ufunc Features

### Specifying output

🌻 For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. 

🌻Rather than creating a temporary array, you can use this to write computation results directly to the memory location where you’d like them to be.

### Aggregates

💮 For binary ufuncs, there are some interesting aggregates that can be computed
directly from the object.

### Outer products

💐Finally, any ufunc can compute the output of all pairs of two different inputs using the outer method. 

💐This allows you, in one line, to do things like create a multiplica‐
tion table: